#!/bin/sh

#chk="valgrind --leak-check=no --read-var-info=yes"
#chk="gdb --args"

$chk ruby -w -I /var/lib/gems/1.8/gems/treetop-1.4.8/lib/ -I /var/lib/gems/1.8/gems/polyglot-0.3.1/lib/ -I ruby-llvm/lib/ pup.rb $*
